set(VER_FILE "${CMAKE_SOURCE_DIR}/Version.txt")
set(CONF_FILE "${CMAKE_SOURCE_DIR}/KIEXConfig.h.in")
	
IF(EXISTS ${VER_FILE})
    file(READ ${VER_FILE} VERSION_STORED)
	separate_arguments(VERSION_STORED)
	list(GET VERSION_STORED 0 MAJOR)
	list(GET VERSION_STORED 1 MINOR)
	list(GET VERSION_STORED 2 PATCH)
	list(GET VERSION_STORED 3 BUILD)
    math(EXPR BUILD "${BUILD}+1")
ELSE()
    set(MAJOR "0")
    set(MINOR "0")
    set(PATCH "0")
    set(BUILD "1")
ENDIF()

file(WRITE ${VER_FILE} ${MAJOR} " " ${MINOR} " " ${PATCH} " " ${BUILD})

string(TIMESTAMP DATE "%Y-%m-%d")
string(TIMESTAMP TIME "%H:%M")

file(WRITE ${CONF_FILE} 
"// Some predefned options and settings for KIEX generated by cmake, and store values. \n\
// Versioning control. \n\
#define KIEX_VERSION_MAJOR ${MAJOR} \n\
#define KIEX_VERSION_MINOR ${MINOR} \n\
#define KIEX_VERSION_PATCH ${PATCH} \n\
#define KIEX_VERSION_BUILD ${BUILD} \n\
\n\
// Compile date and time. \n\
#define KIEX_COMPILE_DATE \"${DATE}\" \n\
#define KIEX_COMPILE_TIME \"${TIME}\" \n\
\n\
")


